---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/23/2018 6:00 PM
---

AddCSLuaFile()

local available_names = {
	'Albert Einstein',
	'Gordon Freeman',
	'Stephen Hawking',
	'Madame Currie',
	'Carl Frederick Gauss',
	'Robert Rosenthal',
	'Robert Openheimer'
}

local function SelectName()
--	if #available_names == 0 then
--		return 'Generic Name Fred'
--	end
	local selected_name_index = math.random(0, #available_names)
	local name = table.remove(available_names, selected_name_index)
	if name == nil then
		return 'Generic Fred Durst'
	else
		return name
	end
end

ENT.Base 			= "base_nextbot"
ENT.Spawnable		= true
ENT.Health = 100
--ENT.Team = nil -- This needs set after being made
--ENT.Name = ''
ENT.Cost = 0

function ENT:Initialize()

	self:SetModel( "models/humans/group02/male_08.mdl" )
	self:SetHealth(100)

	--self.LoseTargetDist	= 2000	-- How far the enemy has to be before we lose them
	self.SearchRadius 	= 1000	-- How far to search for enemies

	if SERVER then
		self:SetDisplayName(SelectName())
	end
--	print("Init got called, current name is "..self:GetDisplayName()..".")
--	print(self.Name)

	self.Cost = math.random(10000, 35000)
--	print(self.Cost)

end

function ENT:SetupDataTables()

	self:NetworkVar( "Int", 0, "Team" )
	self:NetworkVar( "String", 1, "DisplayName" )

end

function ENT:SetCost(cost)
	self.Cost = cost
end

--function ENT:Use( plyActivator, entCaller, numUseType, numInteger )
----	print(plyActivator)
----	print(entCaller)
----	print(numUseType)
----	print(numInteger)
--end

--function ENT:OnTakeDamage( damageInfo )
----	print(damageInfo)
----	PrintTable(damageInfo)
--end

function ENT:OnInjured( damageInfo )
	local attacker = damageInfo:GetAttacker()
	local inflictor = damageInfo:GetInflictor()
	if attacker:IsValid() and attacker:IsPlayer() then
		if attacker:Team() == self:GetTeam() then
			local message = "This scientist is on your team idiot!"
			DynamicStatusUpdate(nil, message, 'error', attacker.Player)
			return
		end -- WHY YO HITTING OUR SCIENTISTS
		local weapon = attacker:GetActiveWeapon()
--		print(weapon)
		if weapon:GetClass() == "weapon_crowbar" then
--			print(attacker.has_scientist)
--			PrintTable(attacker.scientist)
			local success = attacker:PickUpScientist(self:GetDisplayName(), self.Cost, self:GetTeam())
			if success then
				self:Remove()
			end
--			print(attacker.has_scientist)
--			PrintTable(attacker.scientist)
		end
	end
end

----------------------------------------------------
-- ENT:RunBehaviour()
-- This is where the meat of our AI is
----------------------------------------------------
function ENT:RunBehaviour()
	-- This function is called when the entity is first spawned, it acts as a giant loop that will run as long as the NPC exists
	while ( true ) do
		self:StartActivity( ACT_WALK )			-- Walk anmimation
		self.loco:SetDesiredSpeed( 100 )		-- Walk speed
		self:MoveToPos( self:GetPos() + Vector( math.Rand( -1, 1 ), math.Rand( -1, 1 ), 0 ) * 32 ) -- Walk to a random place within about 32 units ( yielding )
		self:HandleStuck()
		self:StartActivity( ACT_IDLE )
		coroutine.wait( math.random(1, 2) )
		self:StartActivity( ACT_BUSY_QUEUE )
		coroutine.yield()
	end

end

--function ENT:OnStuck()
--
--	--local dmginfo = DamageInfo()
--	--dmginfo:SetAttacker( self )
--    --
--	--self:OnKilled( dmginfo )
--
--	--self:MoveToPos( self:GetPos() + Vector( math.Rand( -1, 1 ), math.Rand( -1, 1 ), 0 ) * 200 ) -- Walk to a random place within about 400 units ( yielding )
--	self:StartActivity( ACT_IDLE )
--
--end

list.Set( "NPC", "ram_simple_scientist", {
	Name = "Simple Scientist",
	Class = "ram_simple_scientist",
	Category = "NextBot"
} )
