---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/22/2018 10:16 PM
---

--include( "cl_research_category.lua" )
--include( "cl_research_technology.lua" )

include( "cl_net.lua" )
include( "cl_hooks.lua" )
include( "cl_research_manager.lua" )
include( "cl_utils.lua" )
include( "shared.lua" )
include( "shd_utils.lua" )
include( "shd_hooks.lua" )
include( "cl_player_ext.lua" )
include( "shd_player_ext.lua" )

include( "vgui/cl_hud.lua" )
include( "vgui/cl_pickteam.lua" )
include( "vgui/cl_research_menu.lua" )
include( "vgui/cl_scoreboard.lua" )

local function InitTeamVariables()
    local AllTeams = team.GetAllTeams()
    for ID, TeamInfo in pairs(AllTeams) do
        if (ID ~= TEAM_CONNECTING and ID ~= TEAM_UNASSIGNED and ID ~= TEAM_SPECTATOR) then
            -- These should be client objects.
            local newResearchManager = ClientResearchManager({
                team_index = ID,
                team_name = TeamInfo['Name']
            })
            newResearchManager.status = RESEARCH_STATUS_PREP

            -- key, name, description, cost, tier, reqs, category
            local armorCat = newResearchManager:add_category({
                key = 'armor',
                name = 'Armor',
                icon = "shield alternate icon"
            })

            armorCat:add_technology({
                key = 'armor_one', -- This is required
                name = 'Armor Type I', -- This is required
                description = '20 Armor',
                tier = 1, -- This is required
            })

            armorCat:add_technology({
                key = 'armor_two', -- This is required
                name = 'Armor Type II', -- This is required
                description = '40 Armor',
                tier = 2, -- This is required
                reqs = {'armor_one'}
            })

            armorCat:add_technology({
                key = 'armor_three', -- This is required
                name = 'Armor Type III', -- This is required
                description = '60 Armor',
                tier = 3, -- This is required
                reqs = {'armor_two'}
            })

            armorCat:add_technology({
                key = 'armor_four', -- This is required
                name = 'Armor Type IV', -- This is required
                description = '80 Armor',
                tier = 4, -- This is required,
                reqs = {'armor_three'}
            })

            armorCat:add_technology({
                key = 'armor_five', -- This is required
                name = 'Armor Type V', -- This is required
                description = '100 Armor',
                tier = 5, -- This is required,
                reqs = {'armor_four'}
            })

            local healthCat = newResearchManager:add_category({
                key = 'health',
                name = 'Health',
                icon = "plus alternate icon"
            })

            healthCat:add_technology({
                key = 'health_one', -- This is required
                name = 'Health Type I', -- This is required
                description = '110 Health',
                tier = 1, -- This is required,
            })

            healthCat:add_technology({
                key = 'health_two', -- This is required
                name = 'Health Type II', -- This is required
                description = '120 Health',
                tier = 2, -- This is required
                reqs = {'health_one'}
            })

            healthCat:add_technology({
                key = 'health_three', -- This is required
                name = 'Health Type III', -- This is required
                description = '130 Health',
                tier = 3, -- This is required
                reqs = {'health_two'}
            })

            healthCat:add_technology({
                key = 'health_four', -- This is required
                name = 'Health Type IV', -- This is required
                description = '140 Health',
                tier = 4, -- This is required
                reqs = {'health_three'}
            })

            healthCat:add_technology({
                key = 'health_five', -- This is required
                name = 'Health Type V', -- This is required
                description = '150 Health',
                tier = 5, -- This is required
                reqs = {'health_four'}
            })

            local weapCat = newResearchManager:add_category({
                key = 'weapons',
                name = 'Weapons',
                icon = "fighter jet icon"
            })
            weapCat:add_technology({
                key = 'revolver',
                name = 'Revolver',
                description = 'Mangum Revolver Pistol',
                class = 'weapon_ram_revolver',
                tier = 1
            })

            weapCat:add_technology({
                key = 'shotgun',
                name = 'Shotgun',
                description = 'Basic singlebarrel shotgun',
                class = 'weapon_ram_shotgun',
                tier = 2
            })

            weapCat:add_technology({
                key = 'smg',
                name = 'SMG',
                description = 'A low ROF high dmg SMG',
                class = 'weapon_ram_smg',
                tier = 3,
                reqs = { 'revolver' }
            })

            weapCat:add_technology({
                key = 'ar',
                name = 'Ar2',
                description = 'A high ROF low dmg AR',
                class = 'weapon_ram_ar2',
                tier = 4,
                reqs = { 'shotgun' }
            })

            weapCat:add_technology({
                key = 'crossbow',
                name = 'Crossbow',
                description = 'Classic Crossbow',
                class = 'weapon_crossbow',
                tier = 5,
                reqs = { 'smg' }
            })

            weapCat:add_technology({
                key = 'rpg',
                name = 'RPG',
                description = 'Classic RPG',
                class = 'weapon_rpg',
                tier = 6,
                reqs = { 'ar' }
            })

            weapCat:add_technology({
                key = 'gauss',
                name = 'Gauss Gun',
                description = 'The HL1 Gauss Gun',
                class = 'weapon_ram_gauss',
                tier = 7,
                reqs = { 'crossbow' }
            })

            weapCat:add_technology({
                key = 'egon',
                name = 'Gluon Gun',
                description = 'The HL1 Gluon Gun',
                class = 'weapon_ram_egon',
                tier = 8,
                reqs = { 'rpg' }
            })

            local gadgetCat = newResearchManager:add_category({
                key = 'gadgets',
                name = 'Gadgets',
                icon = "wrench icon"
            })

            gadgetCat:add_technology({
                key = 'satchel',
                name = 'Satchel Charges',
                description = 'Little surprises!',
                class = 'weapon_ram_satchel',
                tier = 1
            })

            gadgetCat:add_technology({
                key = 'grenade',
                name = 'Grenades',
                description = 'Classic Handgrenades',
                class = 'weapon_frag',
                tier = 2,
                reqs = { 'satchel' }
            })

            gadgetCat:add_technology({
                key = 'tripmine',
                name = 'Tripmines',
                description = "Don't walk into the lasers!",
                class = 'weapon_ram_tripmine',
                tier = 3,
                reqs = { 'grenade' }
            })

            local implantCat = newResearchManager:add_category({
                key = 'implants',
                name = 'Implants',
                icon = "microchip icon"
            })

            implantCat:add_technology({
                key = 'legs_one',
                name = 'Cybenetic Legs MKI',
                description = "Walk 25 units faster and run 50 units faster",
                tier = 1
            })

            implantCat:add_technology({
                key = 'legs_two',
                name = 'Cybenetic Legs MKII',
                description = "Walk 50 units faster and run 100 units faster",
                tier = 2,
                reqs = { 'legs_one' }
            })

            TeamInfo.ResearchManager = newResearchManager
            TeamInfo.Money = 30000 -- Every team gets $30,000 to start
            TeamInfo.Scientists = 3 -- Every team gets $30,000 to start
            TeamInfo.ResearchManager:to_JSON()
        end
    end
end

function GM:Initialize()
    -- Do stuff
    MsgN("RM Client initializing...")

    self.BaseClass:Initialize()

    InitTeamVariables()
end

-- Hide the standard HUD stuff
local hud = { ["CCrossHair"] = false, ["CHudHealth"] = true, ["CHudBattery"] = true, ["CHudAmmo"] = true, ["CHudSecondaryAmmo"] = true }

function GM:HUDShouldDraw(name)
    if hud[name] then return false end

    -- Allow the weapon to override this
    local ply = LocalPlayer()
    if (IsValid(ply)) then
        local wep = ply:GetActiveWeapon()
        local team = ply:Team()
--        if team ~= TEAM_ORANGE or team ~= TEAM_BLUE then
        if ply:Team() == TEAM_SPECTATOR or ply:Team() == TEAM_UNASSIGNED or ply:Team() == TEAM_CONNECTING then
            return false
        end
        if (IsValid(wep) and wep.HUDShouldDraw ~= nil) then
            return wep.HUDShouldDraw(wep, name)
        end
    end

    return true
end
