---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/22/2018 10:16 PM
---

include( "shared.lua" )
include( "cl_pickteam.lua" )
include( "cl_researchmenu.lua" )
include( "cl_hud.lua" )

function GM:Initialize()
    -- Do stuff
    MsgN("RM Client initializing...")

    self.BaseClass:Initialize()
end
