---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/22/2018 10:16 PM
---

include( "shd_komerad_autorun.lua" )
AddCSLuaFile( "shd_komerad_autorun.lua" )

if SERVER then
	include("shd_utils.lua")
end
include( "player_class/player_ram.lua" )


GM.Name = "Research & Manufacturing"
GM.Author = "Комерад"
GM.Email = "komeradgygabite@gmail.com"
GM.Website = "https://gmodramteam.github.io/research_and_manufacturing/"
GM.TeamBased = true

RESEARCH_STATUS_WAITING = 0
RESEARCH_STATUS_IN_PROGRESS = 1
RESEARCH_STATUS_VOTING = 2
RESEARCH_STATUS_PREP = 3
RESEARCH_STATUS_MAP_END = 4
RESEARCH_STATUS_CLIENT_VOTED = 5 --- THIS ONE IS SPECIAL!

--[[---------------------------------------------------------
   Name: gamemode:CreateTeams()
   Desc: Note - HAS to be shared.
-----------------------------------------------------------]]
function GM:CreateTeams()

	-- Don't do this if not teambased. But if it is teambased we
	-- create a few teams here as an example. If you're making a teambased
	-- gamemode you should override this function in your gamemode

	if ( not GAMEMODE.TeamBased ) then return end

	TEAM_BLUE = 1
	team.SetUp( TEAM_BLUE, "Blue Team", Color( 0, 0, 255 ) )
	team.SetSpawnPoint( TEAM_BLUE, "info_blue_spawn" ) -- <-- This would be info_terrorist or some entity that is in your map

	TEAM_ORANGE = 2
	team.SetUp( TEAM_ORANGE, "Orange Team", Color( 255, 150, 0 ) )
	team.SetSpawnPoint( TEAM_ORANGE, "info_orange_spawn" ) -- <-- This would be info_terrorist or some entity that is in your map

	team.SetSpawnPoint( TEAM_SPECTATOR, "worldspawn" )

end

function round(num, numDecimalPlaces)
    local mult = 10 ^ (numDecimalPlaces or 0)
    return math.floor(num * mult + 0.5) / mult
end
