---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/27/2018 10:31 AM
---

DEFINE_BASECLASS( "gamemode_base" )

--function GM:PlayerSpawn(ply)
--end

--[[---------------------------------------------------------
	Name: gamemode:PlayerSpawnAsSpectator()
	Desc: Player spawns as a spectator
-----------------------------------------------------------]]
function GM:PlayerSpawnAsSpectator(pl)

    pl:StripWeapons()

    if (pl:Team() == TEAM_UNASSIGNED) then

        pl:Spectate(OBS_MODE_FIXED)
        return
    end

    pl:SetTeam(TEAM_SPECTATOR)
    pl:Spectate(OBS_MODE_ROAMING)
end


--[[---------------------------------------------------------
	Name: gamemode:PlayerDeath()
	Desc: Called when a player dies.
-----------------------------------------------------------]]
function GM:PlayerDeath( ply, inflictor, attacker )
    BaseClass.PlayerDeath( self, ply, inflictor, attacker )
    ply.NextSpawnTime = CurTime() + GetConVar("ram_player_respawn_time"):GetInt()
end

--[[---------------------------------------------------------
	Name: gamemode:PlayerDeathThink( player )
	Desc: Called when the player is waiting to respawn
-----------------------------------------------------------]]
function GM:PlayerDeathThink( pl )

	if ( pl.NextSpawnTime and pl.NextSpawnTime > CurTime() ) then return end

	if ( pl:IsBot() or pl:KeyPressed( IN_ATTACK ) or pl:KeyPressed( IN_ATTACK2 ) or pl:KeyPressed( IN_JUMP ) ) then

		pl:Spawn()

	end

end

--[[---------------------------------------------------------
	Name: gamemode:PlayerSpawn()
	Desc: Called when a player spawns
-----------------------------------------------------------]]
function GM:PlayerSpawn(pl)

    --
    -- If the player doesn't have a team in a TeamBased game
    -- then spawn him as a spectator
    --
    if (self.TeamBased and (pl:Team() == TEAM_SPECTATOR or pl:Team() == TEAM_UNASSIGNED)) then

        self:PlayerSpawnAsSpectator(pl)
        return
    end

    -- Stop observer mode
    pl:UnSpectate()

    pl:SetupHands()

    --player_manager.OnPlayerSpawn( pl )
    --player_manager.RunClass( pl, "Spawn" )

    -- Call item loadout function
    hook.Call("PlayerLoadout", GAMEMODE, pl)
    --    pl:Give("weapon_ram_pistol", false)
    --    pl:GiveAmmo( 125, 3, false )

    -- Set player model
    hook.Call("PlayerSetModel", GAMEMODE, pl)
end

function GM:PlayerSetModel(ply)
    if ply:Team() == TEAM_BLUE or ply:Team() == TEAM_ORANGE then
        if ply:Team() == TEAM_BLUE then
            local mdl = GAMEMODE.playermodel or "models/player/group01/male_07.mdl"
            util.PrecacheModel(mdl)
            ply:SetModel(mdl)

            -- Always clear color state, may later be changed in TTTPlayerSetColor
            ply:SetPlayerColor(Vector(0, 0, 1))
        else
            local mdl = GAMEMODE.playermodel or "models/player/group01/male_06.mdl"
            util.PrecacheModel(mdl)
            ply:SetModel(mdl)

            -- Always clear color state, may later be changed in TTTPlayerSetColor
            ply:SetPlayerColor(Vector(1, 150/255, 0))
        end
    end
end