---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/26/2018 2:16 PM
---

-- Like string.FormatTime but simpler (and working), always a string, no hour
-- support
function util.SimpleTime(seconds, fmt)
	if not seconds then seconds = 0 end

    local ms = (seconds - math.floor(seconds)) * 100
    seconds = math.floor(seconds)
    local s = seconds % 60
    seconds = (seconds - s) / 60
    local m = seconds % 60

    return string.format(fmt, m, s, ms)
end

function round(num, numDecimalPlaces)
    local mult = 10 ^ (numDecimalPlaces or 0)
    return math.floor(num * mult + 0.5) / mult
end

function PrintToTeam(teamIndex, stringMsg)
    for k, ply in pairs(player.GetAll()) do
        if ply:Team() == teamIndex then
            --ply:ChatPrint(stringMsg)
            net.Start("RMPrintToTeam")
            net.WriteString(stringMsg)
            net.Send(ply)
        end
    end
end

function ClientStatusUpdate(intStatus, intTeam)
    net.Start("RMClientStatusUpdate")
    --net.WriteString("some text")
    net.WriteInt(intStatus, 3)
    net.WriteInt(intTeam, 3)
    net.Broadcast()
    -- We did something!
end