---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Комерад.
--- DateTime: 5/30/2018 11:00 PM
---

HUD = {}
HUD.html = nil

function HUD:Init()
    local hud_frame = vgui.Create("DFrame")
    hud_frame:SetTitle("")
    hud_frame:SetSize(ScrW(), ScrH())
    hud_frame:Center()
    --hud_frame:SetPos(0, ScrH() - ScrH() * 0.15)
    hud_frame:ShowCloseButton(false)
    hud_frame:SetDraggable(false)
    hud_frame:SetSizable(false)
    hud_frame:SetPaintShadow(true)
    function hud_frame:Paint()
    end

    self.html = vgui.Create("DHTML", hud_frame)
    self.html:Dock(FILL)
    self.html:OpenURL("asset://garrysmod/gamemodes/research_and_manufacturing/content/html/hud.html")
    self.html:SetAllowLua(true)

    self.html:AddFunction("player", "getInfo", function()
        if LocalPlayer():IsValid() and (LocalPlayer():Team() == TEAM_BLUE or LocalPlayer():Team() == TEAM_ORANGE) then
            local status = team.GetAllTeams()[LocalPlayer():Team()].ResearchManager.status
            local weapon = LocalPlayer():GetActiveWeapon()
            local ammo_data = {}
            local research_timer = {}

            if timer.Exists("RAM_LocalPlayerResearchTimer") then
                research_timer = {
                    show = true,
                    time_left = timer.TimeLeft("RAM_LocalPlayerResearchTimer"),
                    default_time = 35 -- This needs to be a convar...
                }
            else
                research_timer = {
                    show = false,
                }
            end

--            print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
--            PrintTable(research_timer)
--            print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")

            local clip_cur = nil
            local clip_max = nil
            local ammo_total = nil
            local show_crosshair = nil

            if IsValid(weapon) and weapon.DrawAmmo then
                -- Egon and Gauss use ammo a bit differently...
                if weapon:GetClass() == 'weapon_ram_gauss' or weapon:GetClass() == 'weapon_ram_egon' or weapon:GetClass() == 'weapon_ram_tripmine' or weapon:GetClass() == 'weapon_ram_satchel' then
                    clip_cur = weapon:GetAmmoPrimary()
                    clip_max = weapon:GetMaxClip1()
                    ammo_total = weapon:Ammo1()
                    show_crosshair = weapon.DrawCrosshair
                else
                    clip_cur = weapon:Clip1()
                    clip_max = weapon:GetMaxClip1()
                    ammo_total = weapon:Ammo1()
                    show_crosshair = weapon.DrawCrosshair
                end

                ammo_data = {
                    show = true,
                    clip_cur = clip_cur,
                    clip_max = clip_max,
                    ammo_total = ammo_total,
                    show_crosshair = show_crosshair,
                }
            else
                ammo_data = {
                    show = false
                }
            end

            local player_data = {
                health = LocalPlayer():Health(),
                armor = LocalPlayer():Armor(),
                has_scientist = LocalPlayer():GetHasScientist(),
                status = status,
                team_scientist_count = team.GetAllTeams()[LocalPlayer():Team()].Scientists,
                ammo_data = ammo_data,
                research_timer = research_timer
            }
            return util.TableToJSON(player_data)
        end
    end)

    self.html:AddFunction("time", "left", function()
        local map_timer = 0
        local prep_timer = 0
        if timer.Exists("RAM_TimerMapEnd") then
            map_timer = timer.TimeLeft("RAM_TimerMapEnd")
        end
        if timer.Exists("RAM_TimerPrepEnd") then
            prep_timer = timer.TimeLeft("RAM_TimerPrepEnd")
        end
        local time_data = {
            map = map_timer,
            prep = prep_timer,
        }
        return util.TableToJSON(time_data)
    end)

    self.html:AddFunction("researchMenu", "update", function()
--        SyncResearch()
        local ply = LocalPlayer()
        if ply:Team() == TEAM_BLUE or ply:Team() == TEAM_ORANGE then
            local AllTeams = team.GetAllTeams()
            local ResearchManager = AllTeams[ply:Team()].ResearchManager
            local json_data = ResearchManager:ToJSON()
            if json_data ~= nil then
                return json_data
            else
                return util.TableToJSON({})
            end
        end
    end)

    self.html:AddFunction("vote", "send", function(cat_key, tech_key)
        net.Start("RAM_RecordResearchVote")
        net.WriteString(cat_key)
        net.WriteString(tech_key)
        net.SendToServer()
        HUD.html:QueueJavascript([[ EVENTS.trigger('toggle_research_menu') ]])
        --        local current_cursor_status = vgui.CursorVisible()
        gui.EnableScreenClicker((false))
    end)

    print("-- RM HUD Initialized --")
end

function HUD:Draw()
    --    if HUD.html == nil then
    --        HUD:Init()
    --    end
end
